version: '3.8'

services:
  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://192.168.0.24/api
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started

  # Backend Express - menggunakan port 5000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-backend
    restart: unless-stopped
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=optipredict_database
      - JWT_SECRET=optipredict_production_secret
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy  # PERUBAHAN UTAMA
      python-ml:
        condition: service_started

  # Python ML Service - menggunakan port 5001
  python-ml:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    container_name: python-ml
    restart: unless-stopped
    ports:
      - "0.0.0.0:5001:5000"
    environment:
      - FLASK_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=optipredict_database
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy  # PERUBAHAN UTAMA

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: optipredict_database
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    # TAMBAHAN MINIMAL:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
