name: Build and deploy Python app to Azure Web App - optipredict-flask

on:
  push:
    branches:
      - main
    paths:
      - "backend/python/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r backend/python/requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd backend/python
          zip -r ../../release.zip . -x "__pycache__/*" "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set up Python version for deployment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment in deploy job
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies in deploy job
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r backend/python/requirements.txt  # Correct path to requirements.txt in the unzipped folder

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2.2.9
        id: deploy-to-webapp
        with:
          app-name: 'optipredict-flask'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3FBB1600CF2349F59327E935281CBB7E }}
