# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - optipredict-flask

on:
  push:
    branches:
      - main
    paths:
      - "backend/python/**"  # ✅ HANYA TRIGGER JIKA ADA PERUBAHAN DI FLASK
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: optipredict-flask
  AZURE_WEBAPP_PACKAGE_PATH: './backend/python'  # ✅ SET PATH KE FOLDER FLASK
  PYTHON_VERSION: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  # ✅ WORKING DIRECTORY
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            !${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/venv/
            !${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2.2.9  # ✅ DOWNGRADE KE VERSI STABIL
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B246C9CF6DB44CCF88E36BDFEB0572B7 }}
