name: Build and deploy Python app to Azure Web App - optipredict-flask

on:
  push:
    branches:
      - main
    paths:
      - "backend/python/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: List files for debugging
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Files in backend/python:"
          ls -la backend/python/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/python/requirements.txt  # ✅ ABSOLUTE PATH

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./backend/python
            !./backend/python/__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2.2.9
        id: deploy-to-webapp
        with:
          app-name: 'optipredict-flask'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B246C9CF6DB44CCF88E36BDFEB0572B7 }}
